Code review
LukeHankey/the-dot-operators pull request #5
Opened 2023-09-04 20:42 UTC by LukeHankey

- Add spacing for improved readability.
- Ignore some unusual type errors.

- Docstrings can be redone at a later point to include parameters and return values

2023-09-07 02:32 UTC, busterbeam requested changes
Very nicely refactored.  

but as stated in other communiques do not agree with the usage of top level `tiler.py` and `utils.py`/  please state more exacting reasons why this should be the path

2023-09-07 02:32 UTC, busterbeam commented on jigsaw/tiles.py
please do not mix `pygame` and `PIL`. The Tile Sprite is... if you look at the jigsaw-surface branch you will notice that Tile uses very different functionality to the `tessellation.py` logic of better-tiling branch. The tile will hold a single tile from the functions in `tessellation.py`.  

Furthermore I am holding out hope that we will implement multiplayer that will require tessellation logic to be common to server and client not everything crammed into client/GUI. I know you have "actually" put this in top level `tiles.py` but that does not really improve the scenario.

Strong opinion but there is a method to my madness.

2023-09-07 02:32 UTC, busterbeam commented on jigsaw/utils.py
`utils.py` having `get_image` makes some sense as it will expand to have API image caller. but why `regular` function in there? lastly that's an old function that doesn't seperate the scrambler function

2023-09-07 10:00 UTC, LukeHankey commented on jigsaw/utils.py
`utils.py` is just a collection of functions that are not yet put into a fitting place. Everything that was in the `common` module has been refactored to be in `utils.py`. It doesn't make much sense to have a whole module dedicated to functions/classes that don't have a place in the overall project.

2023-09-07 10:04 UTC, LukeHankey commented on jigsaw/tiles.py
Afaik, `pygame` and `PIL` have not been confused. Everything on this branch is in relation to what is in `main`. Once things get merged into `main`, I will then start to worry about other changes that have happened on other branches as to not get confused.

Logically, it makes sense to have the top level module (Jigsaw), and within that you have it's components, `tiles.py` being one of them. If it all fits better in a different submodule, then lets change that. 👍

2023-09-07 10:07 UTC, LukeHankey commented on jigsaw-game/common/__init__.py
> +    sequence: dict[tuple[int, int], Image] = {}
That is true, although nothing has fundamentally changed here except improving readability and removing unnecessary functions. This function performs exactly the same as it did without this change.

2023-09-07 10:12 UTC, LukeHankey commented on jigsaw-game/client/__init__.py
> -        super(JigSaw, self).__init__(size)
Sure, real python is good for a lot of Python stuff. https://realpython.com/python-super/.

`super(JigSaw, self)` is still fine, although that is Python 2 syntax. Python 3 removes the need for that and can go parameterless. This probably could have been caught by `pyupgrade`.

2023-09-07 23:09 UTC, busterbeam submitted a review, later dismissed
As discussed with @LukeHankey Font files apparently seem to not be working on some systems

2023-09-08 06:37 UTC, busterbeam approved these changes

2023-09-08 06:37 UTC, merged