The Secret Code Theme
LukeHankey/the-dot-operators pull request #6
Opened 2023-09-05 05:54 UTC by busterbeam

This should work, needs changes to the regular square tiler, but it can be passed on to the UI

2023-09-05 09:00 UTC, busterbeam commented
last commit failing due to incorrect `type` for one of the function parameters/return. once fixed can be closed

2023-09-05 18:20 UTC, LukeHankey commented
The tiles are not scrambled on start up like they were previously because the tile scrambler is not called. Is this intentional?

2023-09-05 18:29 UTC, busterbeam commented
> The tiles are not scrambled on start up like they were previously because the tile scrambler is not called. Is this intentional?

Yes! before a scrambled image would be spat out by `regular` but instead I've separated the function out.  the scrambling function isn't that good so it is probably best that it's separated as that bit of code is going to get longer.

It's needed for secret_codes to work

2023-09-06 09:17 UTC, LukeHankey commented on jigsaw-game/common/secret_codes.py
> +):
Add a return type here

2023-09-07 16:59 UTC, LukeHankey requested changes
As above.

2023-09-07 18:22 UTC, LukeHankey commented on jigsaw-game/common/secret_codes.py
> +    image: Image.Image, text: str, text_color: tuple[int, int, int] = (0, 0, 0)
No need for `text_color` as doesn't seem to be used in the function.

2023-09-07 18:27 UTC, LukeHankey commented on jigsaw-game/common/secret_codes.py
> +):
```suggestion
) -> Generator[tuple[tuple[int, int], Image | None], None, None]:
```

2023-09-07 20:48 UTC, LukeHankey commented
You still need to import `Generator` from `collections.abc`. The module error type is coming from the return type you just added, where `Image` should be `Image.Image`

2023-09-07 21:01 UTC, LukeHankey approved these changes

2023-09-07 21:02 UTC, merged